Import diffutils v3.7

diff --git a/tests/new-file b/tests/new-file
--- a/tests/new-file
+++ b/tests/new-file
@@ -10,29 +10,32 @@ echo a > a || fail=1
 echo '0a1
 > a' > exp || fail=1
 
-diff -N - a <&- > out; test $? = 1 || fail=1
+returns_ 1 diff -N - a <&- > out || fail=1
 compare exp out || fail=1
 
-diff --unidirectional-new-file - a <&- > out; test $? = 1 || fail=1
+returns_ 1 diff --unidirectional-new-file - a <&- > out || fail=1
 compare exp out || fail=1
 
-diff -N b - < a > out; test $? = 1 || fail=1
+returns_ 1 diff -N b - < a > out || fail=1
 compare exp out || fail=1
 
-diff --unidirectional-new-file b - < a > out; test $? = 1 || fail=1
+returns_ 1 diff --unidirectional-new-file b - < a > out || fail=1
 compare exp out || fail=1
 
 echo '1d0
 < a' > exp || fail=1
 
-diff -N a - <&- > out; test $? = 1 || fail=1
+returns_ 1 diff -N a - <&- > out || fail=1
 compare exp out || fail=1
 
-diff --unidirectional-new-file a - <&- > out; test $? = 2 || fail=1
+# With closed standard input, require an exit status of 2
+# and empty stdout.
+returns_ 2 diff --unidirectional-new-file a - <&- > out || fail=1
+compare /dev/null out || fail=1
 
-diff -N - b < a > out; test $? = 1 || fail=1
+returns_ 1 diff -N - b < a > out || fail=1
 compare exp out || fail=1
 
-diff --unidirectional-new-file - b < a > out; test $? = 2 || fail=1
+returns_ 2 diff --unidirectional-new-file - b < a > out || fail=1
 
 Exit $fail
